root = "."
tmp_dir = ".tmp"

[build]
  cmd = "go build -o ./.tmp/knubaschedulebot ./cmd/knubaschedulebot"
  bin = "./.tmp/knubaschedulebot"
  include_ext = ["go", "sql"]
  exclude_dir = [".tmp", "data"]
  delay = 500
