apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: knubaschedulebot
stringData:
    #ENC[AES256_GCM,data:8y3+qPCmdt1yxHhpt4+Y/0gqW5SzP5cFwnKpxYSRxWtY+ur6,iv:MlgRFcXgfa6GBT/PcTTit+W7zmJlzuQLY7IKnRG23cw=,tag:TqD3kDLVqRYgo4JbKGE2rA==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:B2htQv8950AqH0bD1WVuWK/VOelXlox9sESDRvmhKtIKy+rC6LXX9/Bgsw1R2w==,iv:GewKINA0dTgxO5Ex+iK+TIXhDieDbMooNY9rrEUlenw=,tag:mGf8Jv+qacaQ79XfwTcPRA==,type:str]
    #ENC[AES256_GCM,data:jEMHYeTZkMpq/uj28jx4xv+AVazhB/7IcMgll3D8OLxyibVS0ZvTalk5UbZ8En7aUg==,iv:rRq5zLXKhkQ4t7g3RgrptliAgPqldiB7ehNhoJ20kS0=,tag:MWWAge7stmCgKXaOkHRGXw==,type:comment]
    ADMIN_IDS: ENC[AES256_GCM,data:EKWvUECD5NZgIgwXiUGx4YyzB8kR51Yn1pGY8GqM,iv:/KYGRIemOC1e4gOKBjBV3E8gVnaQir5D36uMVGkrR0w=,tag:dyWvs5YErrzabx+nMzqS6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOHVjV0RZK2lvOThoclpp
            N1daUXNNaTFhRWNuS1dVdDhZVWxlcU9PMWljCnlHcXJOYWFSVnZraG1HY3NnTzUy
            bHowSUhoNjR1TnIra2tTbEVCS2kwclEKLS0tIEF1RERJNllVejMxWVlNdUZiTHFk
            OWJMQ0JWRzR4bTJ0bm1WSjdLcWltaGcK5iLs61f742SmxnDmVgeIKtPEZUU0WWMc
            9r8YDtfqEJZwQJv/+qpuzsDxZ+y4U0Lz8scPZd6moiQpHsbLl8qdPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T23:03:59Z"
    mac: ENC[AES256_GCM,data:88WQc7imCW3tvUWx2nLVnWOzTF9qMqPmn67g4bLdKqE2vH/X6md/35tVPh0+NesF5l/cqdjNJnc/8KCzgltaOYmm1NEnyeKEaTPEg0Pk6v904x/USbP0Shb0XhiPRsV4WqqbBezOjmuCESLn4TwaV35g5HjhfUZp+d0Lb2/nLpk=,iv:fonb20cZ7rKHNJVqETRaRp+jlmkqps4kJAV4+bo8t84=,tag:6Uekihsjl1O1cU44RDMWiA==,type:str]
    version: 3.13.3
