apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knubaschedulebot
  namespace: knubaschedulebot
  labels:
    app: knubaschedulebot
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
